# Generated by Django 2.2.4 on 2019-08-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20190814_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystatus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Category'),
        ),
    ]
