# Generated by Django 2.2.4 on 2019-08-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_category_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='categorystatus',
            old_name='name',
            new_name='status_name',
        ),
    ]
