# Generated by Django 2.2.4 on 2019-08-27 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACHEI_MEU_DONO', 'Achei meu dono'), ('ESTOU_PROCURANDO_MEU_DONO', 'Estou procurando meu dono'), ('FUI_ADOTADO_POR_UM_NOVO_DONO', 'Fui adotado por um novo dono'), ('ENCONTREI_MEU_PET', 'Encontrei meu pet'), ('ESTOU_A_PROCURA', 'Estou à procura'), ('ADOTADO', 'Adotado'), ('PARA_ADOTAR', 'Para adotar')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category Status',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('p', 'Pequeno'), ('m', 'Médio'), ('g', 'Grande')], max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('ENCONTRADOS', 'ENCONTRADOS'), ('PROCURA_SE', 'PROCURA_SE'), ('ADOCAO', 'ADOCAO')], max_length=100, null=True)),
                ('state', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_1', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('category_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Category')),
                ('images', models.ManyToManyField(blank=True, to='pets.Image')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.PetType')),
            ],
        ),
    ]