# Generated by Django 2.2.4 on 2019-08-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20190814_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='data',
        ),
    ]
