# Generated by Django 2.2.4 on 2019-08-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='category_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.CategoryStatus'),
        ),
    ]
