# Generated by Django 2.2.4 on 2019-08-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20190815_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='pets.Image'),
        ),
    ]
