# Generated by Django 2.2.4 on 2019-08-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_auto_20190815_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(blank=True, choices=[('ENCONTRADOS', 'ENCONTRADOS'), ('PROCURA_SE', 'PROCURA_SE'), ('ADOCAO', 'ADOCAO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category_status',
            field=models.CharField(blank=True, choices=[('ACHEI_MEU_DONO', 'ACHEI_MEU_DONO'), ('PROCURANDO_MEU_DONO', 'PROCURANDO_MEU_DONO'), ('FUI_ADOTADO', 'FUI_ADOTADO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='images',
            field=models.ManyToManyField(blank=True, to='pets.Image'),
        ),
        migrations.DeleteModel(
            name='CategoryStatus',
        ),
    ]
