# Generated by Django 2.2.4 on 2019-08-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20190816_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='category_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Category'),
        ),
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACHEI_MEU_DONO', 'Achei meu dono'), ('ESTOU_PROCURANDO_MEU_DONO', 'Estou procurando meu dono'), ('FUI_ADOTADO_POR_UM_NOVO_DONO', 'Fui adotado por um novo dono'), ('ENCONTREI_MEU_PET', 'Encontrei meu pet'), ('ESTOU_A_PROCURA', 'Estou à procura'), ('ADOTADO', 'Adotado'), ('PARA_ADOTAR', 'Para adotar')], max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Category')),
            ],
            options={
                'verbose_name_plural': 'Category Status',
            },
        ),
    ]
